dist: bionic
services: docker
language: bash

env:
  global:
    - PACKAGE_NAME=neonavigation_rviz_plugins
  matrix:
    - ROS_DISTRO_TARGET=kinetic
    - ROS_DISTRO_TARGET=melodic
branches:
  only:
    - master

before_install:
  - curl -sL https://raw.githubusercontent.com/at-wat/gh-pr-comment/master/install.sh | sh -s
script:
  - cp ~/.local/bin/gh-pr-comment .travis/
  - docker build
    -t neonavigation-rviz-plugins
    -f .travis/Dockerfile
    --build-arg ROS_DISTRO=${ROS_DISTRO_TARGET}
    --pull=true ${TRAVIS_BUILD_DIR}
    || (gh-pr-comment "[[#${TRAVIS_BUILD_NUMBER}](${TRAVIS_BUILD_WEB_URL})] FAILED on ${ROS_DISTRO_TARGET}" "docker build failed"; false)
  - docker run --rm -it
    -e TRAVIS_BUILD_NUMBER
    -e TRAVIS_BUILD_WEB_URL
    $(sh <(curl -s https://raw.githubusercontent.com/at-wat/gh-pr-comment/master/env.sh))
    neonavigation-rviz-plugins /catkin_ws/src/${PACKAGE_NAME}/.travis/test.sh

jobs:
  include:
    - stage: test
      env:
        - ROS_DISTRO_TARGET=noetic
      script:
        - BUILD_LINK="[[#${TRAVIS_BUILD_NUMBER}](${TRAVIS_BUILD_WEB_URL})]"
        - |
          docker run -it --rm \
            -v $(pwd):/src:ro \
            alpineros/ros-abuild:3.11-noetic \
            && gh-pr-comment "${BUILD_LINK} PASSED on ${ROS_DISTRO_TARGET}" \
              "Tested on Alpine ROS" \
            || (gh-pr-comment "${BUILD_LINK} FAILED on ${ROS_DISTRO_TARGET}" \
              "Tested on Alpine ROS"; false) \
    - stage: prerelease-test
      if: head_branch =~ ^release-.*$
      env:
        - ROS_DISTRO_TARGET=kinetic COVERAGE_TEST=false
      before_install: curl -sL https://raw.githubusercontent.com/at-wat/gh-pr-comment/master/install.sh | sh -s
      script: .travis/prerelease_test.sh
    - stage: prerelease-test
      if: head_branch =~ ^release-.*$
      env:
        - ROS_DISTRO_TARGET=melodic COVERAGE_TEST=false
      before_install: curl -sL https://raw.githubusercontent.com/at-wat/gh-pr-comment/master/install.sh | sh -s
      script: .travis/prerelease_test.sh
    - stage: prerelease-test
      if: head_branch =~ ^release-.*$
      env:
        - ROS_DISTRO_TARGET=noetic COVERAGE_TEST=false
      before_install: curl -sL https://raw.githubusercontent.com/at-wat/gh-pr-comment/master/install.sh | sh -s
      script: .travis/prerelease_test.sh
