name: ci
on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: read
  issues: write         # hiding bot comments
  pull-requests: write  # hiding bot comments

jobs:
  test:
    uses: alpine-ros/alpine-ros-ci-workflows/.github/workflows/ros1.yaml@main
    with:
      enable-bot-comment: true
      bot-comment-api-base: "https://ghbot-api.at-wat.tokyo"
      enable-codecov: true
    secrets:
      bot-comment-token: "8de53bf1-e41f-42c2-a9d3-a5f6fc92f71c"
      codecov-upload-token: ${{ secrets.CODECOV_TOKEN }}
